version: '3.8'

services:
  autogen-studio:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URI=postgresql://autogen:password@postgres:5432/autogen_studio
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
    depends_on:
      - postgres
    volumes:
      - autogen_data:/app/data
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=autogen_studio
      - POSTGRES_USER=autogen
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  autogen_data:
  postgres_data:
